### PR TITLE
Fix missing ScrapingIds on Seasons and episodes

### PR DESCRIPTION
**Pull request by seertenedos**
Fixes the missing ScrapingIds on season and episodes

### CODE REVIEW

**Comment by jensenkd** [comment]
Thanks @seertenedos!

**Comment by seertenedos** [comment]
@jensenkd is there a reason this was closed without being merged in? Just wondering if it was a mistake or if there was an issue with the change?

**Comment by jensenkd** [comment]
I really have no idea. Lol

**Comment by seertenedos** [comment]
thanks it is working now

**Pull request merged**
